### ISSUE TITLE
When using Postgres having a timestamptz column causes an error

### ISSUE THREAD

**Issue by jamessewell** [ShadowTraffic/requests#1]
When I'm using a timestamp which comes out of `formatDateTime` and a table with a `timestamptz` column I get this error writing to Postgres:

```
Exception in thread "main" org.postgresql.util.PSQLException: ERROR: column "ts" is of type timestamp with time zone but expression is of type character varying
  Hint: You will need to rewrite or cast the expression.
  Position: 55
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2713)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2401)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:368)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:498)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:415)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:190)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:177)
	at next.jdbc.result_set$stmt__GT_result_set.invokeStatic(result_set.clj:669)
	at next.jdbc.result_set$stmt__GT_result_set.invoke(result_set.clj:664)
	at next.jdbc.result_set$fn__4932.invokeStatic(result_set.clj:927)
	at next.jdbc.result_set$fn__4932.invoke(result_set.clj:857)
	at next.jdbc.protocols$fn__4172$G__4150__4181.invoke(protocols.clj:34)
	at next.jdbc$execute_one_BANG_.invokeStatic(jdbc.clj:273)
	at next.jdbc$execute_one_BANG_.invoke(jdbc.clj:257)
	at next.jdbc.sql$insert_BANG_.invokeStatic(sql.clj:41)
	at next.jdbc.sql$insert_BANG_.invoke(sql.clj:31)
	at next.jdbc.sql$insert_BANG_.invokeStatic(sql.clj:38)
	at next.jdbc.sql$insert_BANG_.invoke(sql.clj:31)
	at io.shadowtraffic.generator.postgres_writer.PostgresWriter.send_event(postgres_writer.clj:17)
	at io.shadowtraffic.generator.entrypoint$run_iteration_BANG_.invokeStatic(entrypoint.clj:80)
	at io.shadowtraffic.generator.entrypoint$run_iteration_BANG_.invoke(entrypoint.clj:73)
	at io.shadowtraffic.generator.entrypoint$generate_data_BANG_.invokeStatic(entrypoint.clj:118)
	at io.shadowtraffic.generator.entrypoint$generate_data_BANG_.invoke(entrypoint.clj:84)
	at io.shadowtraffic.generator.entrypoint$run_it.invokeStatic(entrypoint.clj:165)
	at io.shadowtraffic.generator.entrypoint$run_it.invoke(entrypoint.clj:157)
	at io.shadowtraffic.generator.entrypoint$_main.invokeStatic(entrypoint.clj:191)
	at io.shadowtraffic.generator.entrypoint$_main.doInvoke(entrypoint.clj:179)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at io.shadowtraffic.generator.entrypoint.main(Unknown Source)
	```

**Comment by MichaelDrogalis** [comment]
Thanks for raising this!

The Postgres driver I'm using doesn't coerce strings into timestamps automatically, so I've added a new [toInstant](https://docs.shadowtraffic.io/reference/generators/date/time/toInstant/) function in `0.0.31` that does the conversion.

Example usage:

```json
{
  "_gen" : "toInstant",
  "ms" : {
    "_gen" : "now"
  }
}
```
